// Do not edit this file manually
export const enabledBlocks = [
  'openai',
  'zemantic-ai',
  'cal-com',
  'chat-node',
  'instantchat',
  'qr-code',
  'dify-ai',
  'mistral',
  'elevenlabs',
  'pause',
] as const
